version: '3.7'

networks:
  default:
    external:
      name: zeta

services:
  
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - zeta
    environment:
      - MYSQL_DATABASE=tools
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

  api:
    container_name: api
    build:
      context: ./node
      dockerfile: ./node/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:3000/"]
      interval: 60s
      timeout: 5s
      retries: 5
    networks:
      - zeta

  web:
    image: nginx
    container_name: webservice
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/block_ips.conf:/etc/nginx/conf/block_ips.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - mysql
    networks:
      - zeta

